front:
  image: nginx
  volumes:
    - ".:/usr/share/nginx/html"
  ports:
    - "80:80"

server:
  image: node:0.12.7
  command: sh -c "cd /var/app/server && npm start"
  volumes:
    - ".:/var/app/server"

kuzzle:
  image: kuzzleio/kuzzle:alpha
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
  command: elasticsearch --cluster.name=tournament

